# config/config.yaml

# Data configuration
data:
  raw_dir: "data/raw/"
  processed_dir: "data/processed/"
  checkpoint_dir: "data/checkpoints/"
  train_file: "fraudTrain.csv"
  test_file: "fraudTest.csv"

# Model configuration
model:
  random_state: 42
  test_size: 0.2
  cv_folds: 5
  high_cardinality_threshold: 10

# Feature engineering
features:
  datetime_features: true
  amount_features: true
  geographic_features: true
  category_encoding: true

# Model parameters
models:
  logistic_regression:
    max_iter: 1000
    random_state: 42
  
  random_forest:
    n_estimators: 100
    random_state: 42
    n_jobs: -1
  
  gradient_boosting:
    n_estimators: 100
    random_state: 42

# Output configuration
output:
  models_dir: "models/"
  reports_dir: "reports/"
  save_predictions: true
  save_feature_importance: true